### ISSUE TITLE
Removing authentication, keep write files

### ISSUE THREAD

**Issue by chiotis** [Falafel65/mavo-php#10]
Hello and thanks for this nice mavo plugin.

I was messing with your code trying to remove authentication (make it work like the local storage mode does), but still using php to write files on server. Unfortunately couldn't make it.
I would appreciate any help and what to remove and make it work.

(I come from the designers world and my skills on coding are very primitive, so forgive me if the answer to my question is very obvious)

**Comment by Falafel65** [comment]
Sorry, forgot to check my github for a while.

If you want to remove authentication (which you shouldn't not because of the write ability) you may have to only comment line 9 and 11, to leave the `$isLogged = true;`

**Comment by chiotis** [comment]
Did this in mavo-backend.php but unfortunately it doesn't do the trick.
My sample app is located here https://arkdrop.app/demo/ and it seems to stuck on an logged out state, without the login button do anything
mv-mode is in edit, but it needs to login to turn the save functionality on.

**Comment by Falafel65** [comment]
Ok, I think I found it, it's missing some data that are set in login.php in $_SESSION.
At line 116 (`$finalData = $_SESSION['user'];`), you'll have to define the user data in an array, something like `$finalData = array(
  'login' => 'login',
  'name' => 'User Name',
  'isLogged' => true
);` 
(sorry, the indent is lost in this editor)
The most important part is the "isLogged" key, used in mavo-php.js:114, set in :78

**Comment by chiotis** [comment]
Thank you so much for your help!
I better understood the logic behind it.
Seems to do the trick.
This approach gives the login/logout links the "enable/disable edit" functionality, which seems fine (ux-wise)
