### ISSUE TITLE
Question mavo-php  backend to save in specific location. 

### ISSUE THREAD

**Issue by winniejo** [Falafel65/mavo-php#11]
Hay Falafel 65 , I am using the mavo-php plug in and its working 
I only struggle with the location where it saves images files (mv-portfolio app) .

I Uploaded al your php files at the top level but it puts al image uploads 
also at the top level.
 
My mv-storage is set to datas/randomname.json  would that not also be 
the location to store image files to ?
 mv-app="portfolio" 
 mv-storage-type="php" 
 mv-storage="datas/randomname.json">
 
I have low level knowledge of PHP so any help would be really appreciated. 
btw Thanks for your work

Winn

**Comment by Falafel65** [comment]
Ah, good one! 

It's supposed to follow the path of the image with the $_GET['path'] property, but I can't remember how is it set (or not) within the JS.
I'll try later to find how it is working, and add some explanations.

**Comment by Falafel65** [comment]
Ok, found it ! 😄 

The [storage part of the Mavo doc](https://mavo.io/docs/storage#uploads) state that you could use  the mv-uploads property on your markup. This info is sent to the backend, and if your path exists and is writeable, it use it.

So, for an image, if you want to store it into `images/portfolio`, you have to set it like this `<img property="img"  mv-uploads="images/portfolio/" />`

**Comment by winniejo** [comment]
Thanks again  Great !!!

**Comment by LeaVerou** [comment]
Do note that if `mv-uploads` is not set, it still sends a default name (`images` for images, `videos` for videos etc). Does that work?

**Comment by Falafel65** [comment]
It does! I wondered at first were the default path came from and discovered from the docs/source.
This helped me discover a little bug in my PHP btw 😅 (I was losing the path in case of duplicate filename)

**Comment by winniejo** [comment]
Great work Thanks !!
