### ISSUE TITLE
Edit mode not working 

### ISSUE THREAD

**Issue by GalinhaLX** [Falafel65/mavo-php#12]
Bonjour @Falafel65 

I've been able to install this plug in, and read data.json file correctly

But I'm not able to edit properties and save data (despite correct file permissions)

I guess it's the same cause @LeaVerou and @DmitrySharabin
are talking about in another plugin [here](https://github.com/mavoweb/plugins/issues/112)

I get this error:
![image](https://user-images.githubusercontent.com/89095737/206570359-e7b9ecc6-3f9b-4fd2-9e80-64ce1801ac45.png)

**Comment by Falafel65** [comment]
Hi @GalinhaLX 

I pushed a refactor that should fix this.

Let me know if it's good for you too !

**Comment by GalinhaLX** [comment]
Bonjour @Falafel65 

Merci pour cette mise à jour!

Questions complémentaires car je ne suis pas complétement sûr de comprendre ce qui ce passe via PHP:

- Quel est le processus exact d'une requête et d'une réponse (entre le navigateur, et le serveur PHP)
Sur mon serveur PHP, j'ai un répertoire contenant mes fichiers .json
J'ai ajouté un fichier .htaccess pour bloquer l'accès extérieur

```
order allow,deny
deny from all
```

Depuis: le navigateur me répond qu'il n'arrive pas à accéder directement au fichier json

=> N'est ce pas le backend avec "mavo-backend.php" qui est côté serveur qui accède aux données JSON, puis les transmet à "mavo-php.js" qui est côté client?

Merci

**Comment by GalinhaLX** [comment]
Bonjour @Falafel65 

Merci pour cette mise à jour!

Problème:

J'ai crée une simple application mavo sous index.html

Lorsqu'on effectue le login, cela envoie sur login.php (ok)

En cas de succès, cela renvoie bien sur la page index.html (ok)

sauf que la barre mavo, affiche toujours 'login'

=> Je dois de nouveau cliquer dessus, et c'est à ce moment là que la barre mavo, cache 'login' pour afficher 'edit' /'save'/'logout'

=> Est-il possible d'afficher cette la barre mavo directement en mode 'edit'/'save'/'logout'?

**Comment by Falafel65** [comment]
Avec plaisir !

J'ai eu le même problème lors de mon utilisation (y compris avec la version précédente), il faut cliquer 2 fois pour apparaître loggé.
En fait la vérification si loggé ne se fait simplement pas au chargement de l'instance à cause de l'appel "passif" du login dans le constructeur, ce qui évite un A/R au PHP dès le début. Potentiellement, en changeant cette appel cela pourrait avoir le comportement recherché.

**Comment by Falafel65** [comment]
Il y avait une autre question que je ne vois pas ici actuellement : 

> Questions complémentaires car je ne suis pas complétement sûr de comprendre ce qui ce passe via PHP
> N'est ce pas le backend avec "mavo-backend.php" qui est côté serveur qui accède aux données JSON, puis les transmet à "mavo-php.js" qui est côté client?

J'avais eu le même questionnement lors du développement initial ! 
Dans cette implémentation, c'est Mavo qui fait quasiment tout le boulot, et ici le backend ne gère que l'écriture en mode brut (le contenu est envoyé déjà formaté au serveur). 
Ce qui implique que si le contenu référencé dans mv-storage n'est pas accessible pour le client directement, il ne peut pas être affiché.

**Comment by GalinhaLX** [comment]
>  J'ai eu le même problème lors de mon utilisation (y compris avec la version précédente), il faut cliquer 2 fois pour apparaître loggé.
> En fait la vérification si loggé ne se fait simplement pas au chargement de l'instance à cause de l'appel "passif" du login dans le constructeur, ce qui évite un A/R au PHP dès le début. Potentiellement, en changeant cette appel cela pourrait avoir le comportement recherché.

Qui fait l'appel ? Mavo ou mavo-php.js?

**Comment by GalinhaLX** [comment]
> Dans cette implémentation, c'est Mavo qui fait quasiment tout le boulot, et ici le backend ne gère que l'écriture en mode brut (le contenu est envoyé déjà formaté au serveur).
> Ce qui implique que si le contenu référencé dans mv-storage n'est pas accessible pour le client directement, il ne peut pas être affiché.

Du coup c'est moi qui suis perdu:
Comment protéger l'accès au fichiers JSON? pour être sûr qu'un autre utlisateur avec le lien , ne puisse ni lire, ni modifier le JSON?

(D'ou ma suggestion d'utiliser Laravel, et de développer un plugin pour Laravel)

**Comment by Falafel65** [comment]
>> Potentiellement, en changeant cette appel cela pourrait avoir le comportement recherché.

> Qui fait l'appel ? Mavo ou mavo-php.js? 

C'est l'adaptateur, donc mavo-php.js (ligne 17).
En passant à this.login(false) ça devrait forcer la vérification.

> Comment protéger l'accès au fichiers JSON? pour être sûr qu'un autre utlisateur avec le lien , ne puisse ni lire, ni modifier le JSON?

L'écriture est protégée par la phase de login. Lire ne devrait pas être protégé plus que l'accès à l'instance Mavo en tant que telle.
La doc de création d'un backend Mavo n'y invite pas spécialement, mais cela peut être géré via la surcharge de la méthode get

**Comment by Falafel65** [comment]
Et après un test rapide, en forçant le login vérifié, on est redirigé vers la page de connexion tant qu'on est pas connecté. Ce qui n'est pas tout à fait une bonne chose.

Ceci dit, le problème de départ est réglé, on ferme ici.

---

The original problem is solved, the rest of the conversation is about another things : 
 - autologin in Mavo when you are back from the login page
 - secure the data retrieving by using the adaptor to access server files
